### PR TITLE
build: add build patch for osx build

### PR DESCRIPTION
**Pull request by chenrui333**
build patch for osx build

previous effort, #69
relates to https://github.com/Homebrew/homebrew-core/pull/126026

### CODE REVIEW

**Comment by plougher** [comment]
First resubmit it *without* any whitespace changes, and I *may* consider it.

Otherwise no.  Whitespace changes are noisy and they're not what this pull request is purporting to be.  I don't think MacOS requires whitespace changes to build?  So they're rude and unnecessary.

As I said, get rid of them and I may consider this pull request.

**Comment by chenrui333** [comment]
> First resubmit it _without_ any whitespace changes, and I _may_ consider it.
> 
> Otherwise no. Whitespace changes are noisy and they're not what this pull request is purporting to be. I don't think MacOS requires whitespace changes to build? So they're rude and unnecessary.
> 
> As I said, get rid of them and I may consider this pull request.

yeah, that makes sense, let me remove those whitespaces. 😅

**Comment by chenrui333** [comment]
@plougher updated.

**Comment by plougher** [comment]
Thanks :-)  I use git blame a lot to discover when code was written.   Some of the older code 10 - 20 years old is littered with whitespace issues, but, I prefer to keep the blame history of when it was written, and not have it looking like new code due to whitespace changes.

When looking for regressions or bugs it is often important to know what code has changed recently or hasn't changed for many years.

**Comment by chenrui333** [comment]
> Thanks :-) I use git blame a lot to discover when code was written. Some of the older code 10 - 20 years old is littered with whitespace issues, but, I prefer to keep the blame history of when it was written, and not have it looking like new code due to whitespace changes.
> 
> When looking for regressions or bugs it is often important to know what code has changed recently or hasn't changed for many years.

no worries, I found it sometime annoying as well, but in the long run, it would be helpful though :)

**Comment by chenrui333** [comment]
Any appetite merging this?

**Comment by chenrui333** [comment]
let me remove those

**Pull request merged**
