### PR TITLE
Debian patches

### PR DESCRIPTION
**Pull request by mattst88**
I realized that most of the patches we carry in Gentoo are just copied from Debian. Many have already been sent upstream to the SF.net mailing list, and many (all?) are part of the [squashfskit](https://github.com/squashfskit/squashfskit) fork.

### CODE REVIEW

**Comment by plougher** [comment]
Thanks for the patches Matt.  I'll have a look over them and see which ones I can and/or want to take.  Some of them I've already implemented.

But two initial questions here which will help me decide on two of the patches.

1. The "unsquashfs: add support for LZMA magics" patch

Why are you including this patch in Gentoo?  It's for an unofficial variant of the Squashfs 3.0 era filesystem.   So it is at least 10 years old, and only then for embedded systems that used that hack back then.

Even embedded systems have long since moved on from Squashfs 3.0 era filesystems and kernels.

This patch is as far I know obsolete, and has been for a long time.

2. The " Fix build failures on Debian/kFreeBSD" patch

This patch is intended to make squashfs-tools compile on non-Linux systems.  As far as I know Gentoo is a purely Linux distribution.  So why do you need it?

My stance on these kind of patches has always been the same.  If I can't personally test it, then I won't take it.  I don't want to get into the business of carrying patches that I can't and don't test.    Every release I try to test everything is OK, and I don't want to take patches that I know I can't test at this point.

There are down-stream forks of the squashfs-tools that add these kind of patches, that is their  raison d'etre.   I'm very happy that they do, and they're in a far better position than I am to test them as they presumably have these systems.  Given this I see no need to start pretending to support non-Linux systems.

**Comment by plougher** [comment]
I forgot to mention, Squashfs 3.0 filesystems date from 2006-2008, and the last Linux kernel that supported them was pre 2.6.29.   So that patch and everything to do with it is now ancient history.

**Comment by mattst88** [comment]
> Thanks for the patches Matt. I'll have a look over them and see which ones I can and/or want to take. Some of them I've already implemented.
> 
> But two initial questions here which will help me decide on two of the patches.
> 
> 1. The "unsquashfs: add support for LZMA magics" patch
> 
> Why are you including this patch in Gentoo? It's for an unofficial variant of the Squashfs 3.0 era filesystem. So it is at least 10 years old, and only then for embedded systems that used that hack back then.
>
> Even embedded systems have long since moved on from Squashfs 3.0 era filesystems and kernels.
> 
> This patch is as far I know obsolete, and has been for a long time.

It looks like we're just applying everything from Debian as-is. I don't think there's much thought in it. I'm happy to drop the patch, we've already made progress on reducing the delta :)
 
> 1. The " Fix build failures on Debian/kFreeBSD" patch
> 
> This patch is intended to make squashfs-tools compile on non-Linux systems. As far as I know Gentoo is a purely Linux distribution. So why do you need it?

Gentoo does support a GNU userland on a FreeBSD kernel, but that's beside the point. We're just applying everything from Debian. Happy to drop that one as well.

> My stance on these kind of patches has always been the same. If I can't personally test it, then I won't take it. I don't want to get into the business of carrying patches that I can't and don't test. Every release I try to test everything is OK, and I don't want to take patches that I know I can't test at this point.

Agreed.

> There are down-stream forks of the squashfs-tools that add these kind of patches, that is their raison d'etre. I'm very happy that they do, and they're in a far better position than I am to test them as they presumably have these systems. Given this I see no need to start pretending to support non-Linux systems.

That's fair. If you're interested you can get multi-platform testing via Travis CI on GitHub (see https://docs.travis-ci.com/user/multi-os/), but I can certainly understand not wanting code in the tree that you cannot personally test.

**Comment by plougher** [comment]
Patches

unsquashfs: Preserve times on symlink inodes

unsquashfs: Attempt to set the sticky bit even when unprivileged

Merged and committed.

But "unsquashfs: Attempt to set the sticky bit even when unprivileged" had a nasty bug which needed fixing

See commit https://github.com/plougher/squashfs-tools/commit/b00547db84688bb05207322d24684aec99384861

**Comment by mattst88** [comment]
Thank you! Feel free to close this merge request when you feel like you've got everything you want upstream.

**Comment by plougher** [comment]
All other patches (the SOURCE_DATE_EPOCH and -fstime patches) have been merged via new implementations.

These needed new implementations due to conflicting requests (I have been asked to implement the options in a couple of ways, with patches that were mutually incompatible), issues with code reuse (all the patches could be slimmed down by over 70% by using existing functionality, rather than adding additional parallel implementations), plus there were a number of bugs (Squashfs uses an unsigned int to store time, not a time_t, and so it is incorrect to accept a time_t and range check against that).

**Comment by ao2** [comment]
>     1. The "unsquashfs: add support for LZMA magics" patch
> 
> 
> Why are you including this patch in Gentoo? It's for an unofficial variant of the Squashfs 3.0 era filesystem. So it is at least 10 years old, and only then for embedded systems that used that hack back then.
> 
> Even embedded systems have long since moved on from Squashfs 3.0 era filesystems and kernels.
> 
> This patch is as far I know obsolete, and has been for a long time.

Hi @plougher I am glad to see squashfs-tools being refreshed!

About the LZMA magics patch (which I was also proposing in https://sourceforge.net/p/squashfs/patches/20/) I think the rationale to have it merged was to be able to unpack old images extracted from firmware files or from flash dumps for analysis purposes, not for actually using those formats in new systems.

If this makes some sense I may try to dig such old images to re-test the change.

Thanks,
   Antonio

**Pull request closed without merging**
