### PR TITLE
unsquashfs: return exit 1 if writing fails for some reason

### PR DESCRIPTION
**Pull request by mvo5**
When using unsquashfs in scripts it is desirable to know if the
unsquashfs was successful or not. Currently only a limited set
of errors are reported via the exit code (e.g. unsupported
compression or invalid superblocks). However it would be great
if failures to write to the target directory (e.g. because of
out-of-space or permission issues) are reported.

This patch is doing that in a somewhat naive approach. I'm happy
to rework the patch. One option could be to reuse BAD_ERROR() in
unsquashfs and stop extracting as soon as a write error happens.
Another one might be to have FAIL_ERROR() that makes the
"FAILED = 1" part of the macro. I'm open for suggestions.

Also if there are concerns about backward compatibility I can
put this beinde a "-strict" (or similar) commandline flag.

This should also fix:
 https://github.com/plougher/squashfs-tools/issues/1

### CODE REVIEW

**Comment by mvo5** [comment]
@Dr-Emann Indeed, sorry for that. My editor screwed that up. Should be fixed now. Please let me know if there is anything else I can do for this PR.

**Comment by mvo5** [comment]
Just a friendly ping if I can do anything to move this PR forward :)

**Comment by plougher** [comment]
Hi Michael

Thanks for the ping.   I work as a kernel maintainer for a large enterprise Linux vendor as my day job.   For the last 6 months or so, I have been very busy in my day job, and so I have had very little time for Squashfs.  Most frustratingly as "it" is still highly confidential, I can't explain why or what.  Go talk to your (Canonical)  Linux kernel maintainers is all I can say.

But an absence of 6 months in replying to Squashfs issues is painful for me.  So I'm replying now due to your ping.

I'm not happy with your patch, as I think there's a better patch that can be applied.  But I'm not currently in a position to do anything better, and so I'll accept your patch, and improve it later.

**Comment by mvo5** [comment]
Thank you @plougher ! I totally understand that you are busy, sorry if I (might have) sounded pushy. Thanks again.

**Pull request merged**
