### PR TITLE
add -half-fragments

### PR DESCRIPTION
**Pull request by abo-junghichi**
If fragment buffer is used for a big fragment bigger than half of block size, there is a risk that fragment buffer is flushed to create a fragment block smaller than the big fragment.
For a spiteful example, consider creating squashfs image with the shell script below.

#!/bin/bash
for ((i=0;i<1000;i++))
do
        echo $i > $i.a
        dd if=some_large_text_file of=$i.b bs=1 count=4095 skip=$i
done
mksquashfs *.a *.b test.sq -b 4k

This script creates 2000 files and a squashfs image with 2000 fragment-blocks.
It means the ability of fragment-block is killed since each of them contains only one file, though each *.a file is smaller than 5 bytes.

Limiting fragment buffer for fragments smaller than or equal to half of block size ensure that each fragment-block except last one gets uncompressed size at least half of block size and contains at least two fragments.
With -always-use-fragments, -half-fragments ensure all blocks (including normal blocks containing one fragment) except last fragment-block has uncompressed size at least half of block size, sinse all fragments smaller than half block size is pushed into fragment buffer.
Limiting fragment buffer for more smaller fragments hurts this minimal uncompressed block size.
So I think there are no needs for other size option.

### CODE REVIEW

**Comment by Dr-Emann** [comment]
I've only recently started looking into squashfs, so apologies if this recommendation is impossible or woudln't work.

The way I would think this could be solved is by keeping a small list of fragment blocks being actively built, with one always under 50% full. When adding a new fragment, this list is searched, and the fragment is added to the block it fits best in (the one it fits in, while leaving the least amount of space). If no block can be found which can fit the new fragment, the block which is most full is flushed, and a new block is created for the new fragment. If there is no longer a block under 50% full, the most full block is flushed, and a new block is started.

**Comment by plougher** [comment]
I will first comment on this

> The way I would think this could be solved is by keeping a small list of fragment blocks being actively built, with one always under 50% full. When adding a new fragment, this list is searched, and the fragment is added to the block it fits best in (the one it fits in, while leaving the least amount of space). If no block can be found which can fit the new fragment, the block which is most full is flushed, and a new block is created for the new fragment. If there is no longer a block under 50% full, the most full block is flushed, and a new block is started.

This is a bad idea, it destroys compression ratio and I/O performance.

When I first implemented fragments (in about 2003), I experimented with exactly this approach and rejected it for the previously mentioned reasons.  While you might think this approach producing more optimally packed fragments will produce better compression it does the exact opposite, and significantly reduces I/O performance too.  I suspected it wouldn't work but had to try it anyway.

This is counter-intuitive.  So I will explain.  First I need to explain a central concept of filesystem's theory, that of "locality of reference".  Put simply "locality of reference" refers to the fact that files in the same directory are often retrieved at the same time, and are often similar in content.  For this reason filesystems try to preserve this locality of reference, and place files in the same directory close together.

The optimal "bin-packing" approach destroys this locality of reference.  It does this both for I/O and compression.

First consider I/O.   By putting files in the "best fit" fragment it means files in the same directory are put into different fragments, and these fragments become written long after the bulk of the directory (as fragments are kept open).  For I/O this results in many more fragments needing to be read, and the disk seek-time increases as they're not close to the directory.   For example say we have files A B C and D in a directory.  With only one fragment they're written to the same fragment, and this fragment will be written close to the other files in the directory.  If we read file A, the fragment containing file A is read.  If we then read files B C and D, they've already been read as they're in the same fragment.  If on the other hand due to "optimal bin packing" files A B C and D have been placed in different fragments, to read all files now need four fragments to be read and decompressed.  Result, a significant reduction in I/O performance.

Second consider compression.  Best compression is achieved by packing similar files together in a fragment.   Locality of reference provides that similar file hint, or in other words files in the same directory are likely to be more similar to each other, than files in a different directory.  From the previous paragraph you should be able to guess what happens when files in the same directory are not placed in the same fragment, but are distributed around fragments with dissimilar files using a "best fit" criteria.  You get significantly worse compression.

**Comment by Dr-Emann** [comment]
Thanks for the response, it's really cool to see a response from the author.

I certainly understand the issue of having too many fragment blocks open. While I originally specified 'a small list' of open fragment blocks, the more I think, the more it seems just two would be sufficient: at least one of which is always less than 50% full.

It would seem to be the best of both worlds: It enables fragment use for all sizes of fragments, but makes sure all fragment blocks are at least 50% full (except the last). Almost all fragments in a directory will still remain pretty close together, most of the time. In the worst case I can think of, you almost fill one of the blocks with N bytes (> blocksize/2), then all further fragments are between N+1 and blocksize (filling, and flushing the other open block repeatedly, since it will be the most full). In that case, it is possible to for some fragments to land quite far from their source directories. 

In the case of the set of files described in the original issue (alternating files of size ~5 bytes, and 1 byte less than the block size), it seems to work ideally. The large fragments will be each in their own block, and the small fragments will be together, sequentially, which should compress much better than a large number of 5 byte blocks.

**Comment by plougher** [comment]
Now a comment on the parent, the introduction of a half fragments option, and the other suggested options.  I'm impressed this is nice work.

Good points: I have long been aware of the need for finer fragment tuning.  In fact it has surprised me that this issue hasn't arisen earlier.

Bad point 1: this really isn't the way to do it.  As you've spent time implementing these options you'll almost certainly disagree with me here.  This I can't help.

Bad point 2: there is an advanced implementation already hiding in Mksquashfs which does the work of these patches and more.

This is called the "actions" code.  I spent 3 years implementing it, but I left it undocumented at the last official release of Squashfs-tools in May 2014.  Why?  Because that release had already taken 3 years out of my life, and I desperately needed to finish it and release it and move on to something else.  Documentation of the new feature at this point was simply too much effort.

I daresay I will have to finally get around to documenting the new feature hiding in Mksquashfs for the last three years.

I will probably also have to explain why I had to do it that way, rather than do it the way these patches do it, which is adding specific options for specific cases.  But at least a comment in one of these patches here has already explained the rationale.

Viz "It seems to provide better compression in almost any case, so I decided do not add separate option (we have too many options already)."

You don't say.  That's the problem with adding specific options for specific use-cases, you simply end up with lots and lots of options, and ultimately, it's non-scalable.  You can't add a specific piece of code for every specific use-case that people want.  One day a request for half-fragments comes along with a specific option.  Then another request comes along for another option (with specific code too) that implements min-tails.    Before you know it there's going to be requests for options for quarter fragments, max-tails, perhaps average-tails, and that's only basing the decision what to pack into fragments on the file-size attribute.  Other people notice they don't want files owned by foobar packed into fragments with files owned by barfoo, and want add a specific option based on owner added.  Then it's open season, users having got the message they can ask for specific options based on *any* file attribute, start to ask for fragment inclusion/exclusion based on filename regular expression match, perhaps file mode too (rwx).  Then what do you do about combinations, one user wants files less than X in filesize but only owned by foobar packed into fragments.  Can you add a specific option with specific code for each of these user-cases.  Of course you can't, the code will degenerate into a mess.

I started 6 years ago realising there was a user-case for half-fragments, then I realised there was a user-case for file ranges (16K > filesize < 32K), then I realised there was a user-case for file ownership (having a fragment reserved exclusively for owner X, another for owner Y, could improve both compression and I/O if the filesystem was so ordered it didn't happen due to locality of reference), then there was a user-case for filename matches (e.g. you know files matching *.XYZ collected together into fragments specifically reserved for that match would improve compression ratio due to file similarity over above that obtained by locality of reference).  At this point you realise the options, and the potential combination of options is endless, and can't be dealt with by static user-specific options and code.  Something much more advanced and generic was needed.  Basically a mini programming language, or at least functions or tests (on file attributes) which could be combined with logical operations (and, or, not) into complex expressions which were then evaluated per file to determine fragment inclusion/exclusion.

I added that "mini-programming language" for fragments, including having more than one fragment open at one time, the decision which fragment  a file went into determined by the evaluation of these expressions.  As long as these expressions are chosen carefully it can result in better performance than "locality of reference" alone.

For instance you can do (for inclusion into the "default" open fragment)

fragment if (filesize(<64K) && user(foobar)) || (filesize(>32K)&& user(barfoo)) || (name(*.XZY) && !user(xxx))

Not an expression anyone would probably use, but it shows the complexity of expressions that can be constructed.

I then realised these expressions based on a logical combination of file attribute tests could be applied to more than just decisions of fragment(s) inclusion/exclusion.  They could also be used to decide whether to compress a file or leave it compressed, and more.

This is the actions code, it's been in Mksquashfs for 3 years, undocumented.

**Comment by edo1** [comment]
As far I can see you looked at my commit: 
https://github.com/edo1/squashfs-tools/commit/092ea39e5

I understood your point of view, here is my reasons why I did it such way:
1. I learned action.c code yesterday.
Yes, my wishes could be implemented with it, but it seems that I need to extend language to do that. I decided this way to be too complicated.
I changed only a few lines of mksquashfs.c to do what I want (not only "half-fragments")

2. I assume that the default configurations should be good enough for most cases and mksquashfs utility should be easy to use.
If default behavior is changed all users will get advantages (and disadvantages) of that.
I'm unsure that all buildroot-based systems (like openwrt/lede), various live-USB distributions and so on will use action language.
BTW, I have no idea why anybody could want to do not use "half-fragments"
Current approach increases count of fragments blocks and reduces compression ratio.

3. There already were command-line options to control fragments ("no-fragments", "always-use-fragments").

It is only my opinion. The final decision is yours

P.S. mksquashfs definitely needs better documentation.

**Comment by plougher** [comment]
> I learned action.c code yesterday.
Yes, my wishes could be implemented with it, but it seems that I need to extend language to do that. I decided this way to be too complicated.
I changed only a few lines of mksquashfs.c to do what I want (not only "half-fragments")

If you had learnt the action.c code yesterday (and as it's 3266 lines including a lexical analyser, recursive descent parser, expression evaluator plus specific routes for 55 test operators and actions I sincerely doubt that), then you would know that the actions language isn't complicated as you claim.  

> I changed only a few lines of mksquashfs.c to do what I want (not only "half-fragments")

and then there will be the next person who only wants a little hack here and there for an edge case, and the next, and the next.  It's impossible to make special cases, because everyone thinks they're  "special" and they all deserve special treatment.

> I assume that the default configurations should be good enough for most cases and mksquashfs utility should be easy to use.
If default behavior is changed all users will get advantages (and disadvantages) of that.
I'm unsure that all buildroot-based systems (like openwrt/lede), various live-USB distributions and so on will use action language.
BTW, I have no idea why anybody could want to do not use "half-fragments"
Current approach increases count of fragments blocks and reduces compression ratio.

Because half-fragments is a bogus concept which should never be the default, and should only be allowed on a specific basis if the source filesystem has pathologies, and only under a different name/concept altogether.

I have lost patience with trying to explain my system to you, because you clearly don't want to be told something else.  But I will try again.  But I'm only spending another evening doing this, not out of fun, but because I want to squash the bogus concepts contained in these pull requests.  I will also point out these are facts, and not my opinion as you seem to think.  But sadly many a man will seek to deny facts if the alternative is to admit they're wrong.

A file fragment is simply a length of data which is too small to fill a datablock.  End of.  Anything less than a block size therefore constitutes a fragment,.  If the block size is 4K, then 4095 bytes is a file fragment, as is 1 byte.  To make a distinction between them at the filesystem level is bogus, and is splitting hairs, there is no such thing as a "half fragment".   Likewise there exists a one-to-one relationship between block size and fragment block size, a file fragment by definition is simply something that doesn't fit into the block size, and therefore the notion of a different fragment block size is bogus.

Therefore any "concepts" like half fragments, and fragment block sizes less than datablock size are bogus, and are imaginings which do not exist in the filesystem specification and layout.  You are conflating fragment fill strategy with the basic concept of fragments, and coming up with a mess.

As far as fragment fill strategy goes, it is right and proper that Mksquashfs packs file fragments (that is anything less than the block size) into fragment blocks by default.  This is mechanism, and it is what fragments is all about.   To suggest that Mksquashfs should only pack "half fragments" into fragment blocks is trying to pretend you can change the definition of what a fragment is.

Yes sometimes the packing of file fragments into fragment blocks exhibits pathologies.  But the pathologies are invariably different and highly specific to the source files.  It is impossible to make Mksquashfs deal with these pathologies on its own.  As I explained in a previous post, as soon as you try to add strategy (rather than mechanism which favours nothing and where you implicitly get the benefits of locality of reference) to Mksquashfs you end up in a mess, with often worse compression and I/O.  It is swings and roundabouts.

You don't fix this by adding bogus concepts of "half-fragments", or fragment block sizes.   You want the user to get to the nub of the problem, which will always be expressed/expressible in terms of file attributes, and then allow the user to change behaviour based on *these* file attributes.

For example rather than the bogus concept of the "-half-fragments" option, this is how you can achieve it right now.

`mksquashfs *.a *.b test.sq -b 4k -action "no-fragments@filesize(>2K)"`

This disables the packing of files more than 2K in size into fragments.

But, as you know it is the *.b files which are causing the pathology, an even better fix is

`mksquashfs *.a *.b test.sq -b 4k -action "no-fragments@name(*.b)"`

This disables the packing of all files matching *.b into fragments.

That's not too difficult to learn or type.  If somebody didn't want to do that, it can always be provided as a solution in a "cheat sheet".

Even better you're using the right concept to address the problem, which is to filter on file attribute.

**Comment by plougher** [comment]
> In the case of the set of files described in the original issue (alternating files of size ~5 bytes, and 1 byte less than the block size), it seems to work ideally. The large fragments will be each in their own block, and the small fragments will be together, sequentially, which should compress much better than a large number of 5 byte blocks.

As I said in a previous post, the easiest way to deal this issue is to simply prevent the *.b files being packed into fragments, or

`mksquashfs *.a *.b test.sq -b 4k -action "no-fragments@name(*.b)"`

But the actions language, as previously mentioned, does allow multiple open fragments to be created.

`mksquashfs *.a *.b test.sq -b 4k -action "fragment(afiles)@name(*.a)"`

Creates an additional fragment stream (i.e. an extra open fragment in parallel to the default open fragment) reserved specifically for files matching *.a.

This creates fragment blocks with all the small fragment files, leaving the default fragment to be filled with the other files.

Both result in almost the same compression.  Except in the one case *.b files are packed into the default fragment (giving 1001 fragments), and in the other case the *.b files are not packed into fragments (giving 1 fragment).

The reported slightly larger filesystem where datablocks are used to store the *.b files is because datablocks generate slightly larger metadata (the datablock index at the end of the inode header), whereas fragment pointers are stored in the inode header.  But this is counter-acted by the fact the fragment index table with 1001 entries will be larger.  But that is not reported in the summary.

`phillip@panopticon:/tmp$ mksquashfs test test.sq -b 4k -action "fragment(afiles)@name(*.a)" -nopad
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on test.sq, block size 4096.
[=====================================================================================================================================================|] 2000/2000 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 4096
	compressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 4025.08 Kbytes (3.93 Mbytes)
	97.65% of uncompressed filesystem size (4122.15 Kbytes)
Inode table size 10596 bytes (10.35 Kbytes)
	16.53% of uncompressed inode table size (64107 bytes)
Directory table size 9146 bytes (8.93 Kbytes)
	35.29% of uncompressed directory table size (25920 bytes)
Number of duplicate files found 0
Number of inodes 2001
Number of files 2000
Number of fragments 1001
Number of symbolic links  0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 1
Number of ids (unique uids + gids) 1
Number of uids 1
	phillip (1000)
Number of gids 1
	phillip (1000)
phillip@panopticon:/tmp$ mksquashfs test test2.sq -b 4k -action "no-fragments@name(*.b)" -nopad
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on test2.sq, block size 4096.
[=====================================================================================================================================================|] 2000/2000 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 4096
	compressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 4026.16 Kbytes (3.93 Mbytes)
	97.95% of uncompressed filesystem size (4110.44 Kbytes)
Inode table size 12300 bytes (12.01 Kbytes)
	18.06% of uncompressed inode table size (68109 bytes)
Directory table size 10647 bytes (10.40 Kbytes)
	41.06% of uncompressed directory table size (25932 bytes)
Number of duplicate files found 0
Number of inodes 2001
Number of files 2000
Number of fragments 1
Number of symbolic links  0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 1
Number of ids (unique uids + gids) 1
Number of uids 1
	phillip (1000)
Number of gids 1
	phillip (1000)
phillip@panopticon:/tmp$ ls -la *.sq
-rw-r--r-- 1 phillip phillip 4122784 Apr 12 08:09 test2.sq
-rw-r--r-- 1 phillip phillip 4121681 Apr 12 08:09 test.sq`

**Comment by edo1** [comment]
> Yes sometimes the packing of file fragments into fragment blocks exhibits pathologies. But the pathologies are invariably different and highly specific to the source files.

I cannot agree with that. You meant that "half-fragments" will work for corner cases only.
But I made tests with different data sets (whole system image, produced by buildroot for ARM, /usr/bin on my desktop x64 system and so on) with both gzip and xz compressions. Always in my tests "half-fragments" provides smaller image size.

**Comment by Dr-Emann** [comment]
> As I said in a previous post, the easiest way to deal this issue is to simply prevent the *.b files being packed into fragments, or
> 
> `mksquashfs *.a *.b test.sq -b 4k -action "no-fragments@name(*.b)"`
>
> But the actions language, as previously mentioned, does allow multiple open fragments to be created.
> 
> `mksquashfs *.a *.b test.sq -b 4k -action "fragment(afiles)@name(*.a)"`

I will never argue that domain specific knowledge will not trump general optimizations every time. If the user knows enough about their data to use the action syntax, they can always make better trade-offs than we can in a general case: The action syntax is incredibly powerful, and does indeed make any 'half fragment', or 'fragment block size' options superfluous. 

However, I would argue that my suggested algorithm (2 open fragment blocks, one always at least 50% free, with new fragments added to the block that is most full that can contain them) is a better default, for when the user doesn't know enough about their data to specify more options, or doesn't care enough to investigate the best possible packing method.

I ran an experiment with 500,000 randomly sized fragments, using both a single open fragment block, and my dual fragment block algorithm. Fragment sizes were picked as floating point values between 0 and 1, and a fragment block is of size 1. 

The single block algorithm resulted in:
```
blocks:           333,045
min packed block: 0.0197
```

The double block algorithm resulted in:
```
blocks:           299,356
min packed block: 0.5007
```

To compare locality: if the `i`th fragment inserted is the `j`th fragment written to disk, let `d = abs(j - i)`.  `d` is in units of fragments, not fragment blocks.
The double block algorithm had the following results:
* The maximum value of `d` was 33.
* The average value of `d` was 1.256
* 87.4% of all fragments had `d` < 3
* 98.4% of all fragments had `d` < 6 (I would expect a fragment has a fair deal in common with a fragment 5 fragments ago)

I personally think that, given that the default behavior must be a trade-off because we cannot do perfectly for every general situation, a double block algorithm strikes a good balance of avoiding tiny fragment blocks, while still keeping pretty good locality.

However, I understand that others may have a different view of where the ideal balance is, and if locality above all else is chosen to remain the default, I understand, it does work quite well in almost all cases.

**Comment by edo1** [comment]
> When adding a new fragment, this list is searched, and the fragment is added to the block it fits best in (the one it fits in, while leaving the least amount of space). If no block can be found which can fit the new fragment, the block which is most full is flushed, and a new block is created for the new fragment

It seems to be enough

> If there is no longer a block under 50% full, the most full block is flushed, and a new block is started.

Is there any advantage of doing that?


I did some test as well. My results are close to yours (difference could be caused by another random generator)

```
Test            Simple  One half-empty
default         333625
half-fragments  324894
2 blocks        294741  299798
4 blocks        279065  280783
8 blocks        269409  269974
16 blocks       262843  263065
32 blocks       258365  258455
64 blocks       255400  255432
128 blocks      253446  253454
256 blocks      252233  252232
512 blocks      251613  251613
1024 blocks     251223  251223
```
(first column is name of the test, second - count of the fragment blocks, third - count of the fragment blocks while keeping at least one under 50% full; there are 500000 of randomly sized fragments as in your test)

As expected, "half-fragments" provides better fragment blocks filling than default approach.
List of fillable fragment blocks provides even better results (I was really surprised how much better it is even with only couple of blocks).

**Comment by Dr-Emann** [comment]
I'm not sure why I initially thought the half empty bin was required. Best fit packing with >1 bin guarantees all bins will be > half full. However, I think it's a useful limit to decrease the maximum age of fragment blocks.

You're optimizing for an irreverent variable. The number of blocks is meaningless, unless it is abnormally high because of a large number of tiny blocks. For the reasons @plougher mentioned, packing the fragment blocks super well is likely to decrease both performance, and compression ratio, as the more open fragment blocks are around, the more best fit fragments will end up far from the other data nearby them, which would be more likely to compress well. (e.g. I'd take a 75% full fragment block comprised of all data from one folder, over a 99% full fragment block comprised of the files from 15 folders any day).

By limiting to 1.5 fragment blocks ensures all fragment blocks are at least half full (to give the compressor enough data to work with), while trying to minimize the distance between fragments natural order (increases in which cause larger latencies when fetching similar files, and may decrease compression ratio as further apart fragments are assumed to be less similar)

**Pull request closed without merging**
